// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjmEgR-MpseHiI7J8xftLIE7I9A4L3vYM',
    appId: '1:785864667265:web:3e91467f73e12a419d9d80',
    messagingSenderId: '785864667265',
    projectId: 'solo-ebike-services',
    authDomain: 'solo-ebike-services.firebaseapp.com',
    storageBucket: 'solo-ebike-services.appspot.com',
    measurementId: 'G-1K47Y7J87C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxZw50T78NZFOuBQe5Nfbg935_vRY5lTk',
    appId: '1:785864667265:android:59ac780912e90cc69d9d80',
    messagingSenderId: '785864667265',
    projectId: 'solo-ebike-services',
    storageBucket: 'solo-ebike-services.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8AomURL3yfKL1yqsaFjDh7pufGezvquE',
    appId: '1:785864667265:ios:22e8dfb3048dcf649d9d80',
    messagingSenderId: '785864667265',
    projectId: 'solo-ebike-services',
    storageBucket: 'solo-ebike-services.appspot.com',
    iosClientId: '785864667265-emrmfvlceg2rdofvft8be7acl6fm4009.apps.googleusercontent.com',
    iosBundleId: 'com.example.trialProject1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8AomURL3yfKL1yqsaFjDh7pufGezvquE',
    appId: '1:785864667265:ios:22e8dfb3048dcf649d9d80',
    messagingSenderId: '785864667265',
    projectId: 'solo-ebike-services',
    storageBucket: 'solo-ebike-services.appspot.com',
    iosClientId: '785864667265-emrmfvlceg2rdofvft8be7acl6fm4009.apps.googleusercontent.com',
    iosBundleId: 'com.example.trialProject1',
  );
}
